eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    region: region-1
    service-url:
      zone1: http://localhost:8761/eureka/
      zone2: http://127.0.0.1:8762/eureka/
    availability-zones:
      region-1: zone1,zone2
spring.profiles.active: zone1
security:
  user:
    name: admin
    password: admin
    role: SYSTEM